FROM nginx:alpine

LABEL maintainer="mirek <mirek@cnl.sk>"
LABEL title="Rambo: Last Blood"
LABEL year="2019"
LABEL description="Rambo must confront his past and unearth his ruthless combat skills to exact revenge in a final mission."
LABEL imdb="https://www.imdb.com/title/tt1206885"
LABEL part="5"

ENV RAMBO_PART=5


RUN rm /etc/nginx/conf.d/*
ADD nginx.conf.template /etc/nginx/conf.d/
ADD index.5.html /usr/share/nginx/html/index.html

ADD images/rambo.5.jpg usr/share/nginx/html/images/rambo.5.jpg
ADD css/rambo.5.css usr/share/nginx/html/css/rambo.5.css

CMD [ "/bin/sh" , "-c" , "sed 's/${RAMBO_PART}/'${RAMBO_PART}'/g' < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/nginx.conf && exec nginx -g 'daemon off;'" ]
