FROM nginx:alpine

# the arguments describing the title
ARG part=1
ARG title="First Blood"
ARG year=1982
ARG description="A veteran Green Beret is forced by a cruel Sheriff and his deputies to flee into the mountains and wage an escalating one-man war against his pursuers."
ARG imdb="https://www.imdb.com/title/tt0083944"

# metadata labels
LABEL maintainer="mirek <mirek@cnl.sk>"
LABEL title="$title"
LABEL year="$year"
LABEL description="$description"
LABEL imdb="$imdb"
LABEL part="$part"

# environment variables
ENV part=$part
ENV title=$title
ENV year=$year
ENV description=$description
ENV imdb=$imdb

RUN rm /etc/nginx/conf.d/*
ADD nginx.conf.template /etc/nginx/conf.d/nginx.conf
# ADD index.$part.html /usr/share/nginx/html/index.html
ADD index.html /usr/share/nginx/html/index.html

ADD images/rambo.$part.jpg usr/share/nginx/html/images/rambo.$part.jpg
# ADD css/rambo.$part.css usr/share/nginx/html/css/rambo.$part.css

RUN sed -e "s/{{TITLE}}/${title}/g" \
        -e "s/{{YEAR}}/${year}/g" \
        -e "s/{{DESCRIPTION}}/${description}/g" \
        -e "s/{{PART}}/${part}/g" \
        -e "s|{{IMDB}}|${imdb}|g" \
        -i /usr/share/nginx/html/index.html
