FROM nginx:alpine

# the arguments describing the title
ARG title="Rambo III"
ARG year="1988"
ARG description="Rambo mounts a one-man mission to rescue his friend Colonel Trautman from the clutches of the formidable invading Soviet forces in Afghanistan."
ARG imdb="https://www.imdb.com/title/tt0095956"
ARG part="3"

# metadata labels
LABEL maintainer="mirek <mirek@cnl.sk>"
LABEL title="$title"
LABEL year="$year"
LABEL description="$description"
LABEL imdb="$imdb"
LABEL part="$part"

# environment variables
ENV part=$part
ENV title=$title
ENV year=$year
ENV description=$description
ENV imdb=$imdb

RUN rm /etc/nginx/conf.d/*
ADD nginx.conf.template /etc/nginx/conf.d/nginx.conf
ADD index.html /usr/share/nginx/html/index.html

ADD images/rambo.$part.jpg usr/share/nginx/html/images/rambo.$part.jpg
# ADD css/rambo.3.css usr/share/nginx/html/css/rambo.3.css

RUN sed -e "s/{{TITLE}}/${title}/g" \
        -e "s/{{YEAR}}/${year}/g" \
        -e "s/{{DESCRIPTION}}/${description}/g" \
        -e "s/{{PART}}/${part}/g" \
        -e "s|{{IMDB}}|${imdb}|g" \
        -i /usr/share/nginx/html/index.html
