FROM nginx:alpine

LABEL maintainer="mirek <mirek@cnl.sk>"
LABEL title="Rambo"
LABEL year="2008"
LABEL description="In Thailand, John Rambo joins a group of mercenaries to venture into war-torn Burma, and rescue a group of Christian aid workers who were kidnapped by the ruthless local infantry unit."
LABEL imdb="https://www.imdb.com/title/tt0462499"
LABEL part="4"

ENV RAMBO_PART=4


RUN rm /etc/nginx/conf.d/*
ADD nginx.conf.template /etc/nginx/conf.d/
ADD index.4.html /usr/share/nginx/html/index.html

ADD images/rambo.4.jpg usr/share/nginx/html/images/rambo.4.jpg
ADD css/rambo.4.css usr/share/nginx/html/css/rambo.4.css

CMD [ "/bin/sh" , "-c" , "sed 's/${RAMBO_PART}/'${RAMBO_PART}'/g' < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/nginx.conf && exec nginx -g 'daemon off;'" ]
