FROM nginx:alpine

LABEL maintainer="mirek <mirek@cnl.sk>"
LABEL title="First Blood Part II"
LABEL year="1985"
LABEL description="Rambo returns to the jungles of Vietnam on a mission to infiltrate an enemy base-camp and rescue the American POWs still held captive there."
LABEL imdb="https://www.imdb.com/title/tt0089880"
LABEL part="2"

ENV RAMBO_PART=2


RUN rm /etc/nginx/conf.d/*
ADD nginx.conf.template /etc/nginx/conf.d/
ADD index.2.html /usr/share/nginx/html/index.html

ADD images/rambo.2.jpg usr/share/nginx/html/images/rambo.2.jpg
ADD css/rambo.2.css usr/share/nginx/html/css/rambo.2.css

CMD [ "/bin/sh" , "-c" , "sed 's/${RAMBO_PART}/'${RAMBO_PART}'/g' < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/nginx.conf && exec nginx -g 'daemon off;'" ]
