FROM nginx:alpine

ARG part=2

LABEL maintainer="mirek <mirek@cnl.sk>"
LABEL title="First Blood Part II"
LABEL year="1985"
LABEL description="Rambo returns to the jungles of Vietnam on a mission to infiltrate an enemy base-camp and rescue the American POWs still held captive there."
LABEL imdb="https://www.imdb.com/title/tt0089880"
LABEL part="$part"

ENV RAMBO_PART=$part


RUN rm /etc/nginx/conf.d/*
ADD nginx.conf.template /etc/nginx/conf.d/
ADD index.$part.html /usr/share/nginx/html/index.html

ADD images/rambo.$part.jpg usr/share/nginx/html/images/rambo.$part.jpg
ADD css/rambo.$part.css usr/share/nginx/html/css/rambo.$part.css

CMD [ "/bin/sh" , "-c" , "sed 's/${RAMBO_PART}/'${RAMBO_PART}'/g' < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/nginx.conf && exec nginx -g 'daemon off;'" ]
